export { default as HomePage } from './Pages/HomePage'
export { default as SummarizerPage } from './Pages/SummarizerPage'
export { default as AboutPage } from './Pages/AboutPage'
export { default as TeamPage } from "./Pages/TeamPage"
export { default as TeamReachOutPage } from './Pages/TeamReachOutPage'
export { default as NavBar } from './NavBar'
export { default as TeamMemberCard } from './TeamMemberCard'
export { default as Modal } from "./Modal/Modal"
export { default as ShareModal } from "./Modal/ShareModal"